### ISSUE TITLE
POST requests

### ISSUE THREAD

**Issue by salas81** [SaMuELToLoKo/homebridge-advanced-thermostat#4]
Are the POST requests actual POST requests? Seems to me they are GET requests. For example:

temperatureTarget is meant to be a POST request but when triggered the URI is "whatevertheespname.local/targetTemperature/whateverthevalue" which is a GET request.

Am I getting something wrong?

**Comment by SaMuELToLoKo** [comment]
Hello, first of all thanks for your comments.

This plugin uses POST to set the temperature target to the NODE, and uses GET to get the temperature target from it. For example

If you are getting the current state from your node (whichever it is) it uses GET.

But if instead of asking to it you want to set a new state the plugin will use POST to communicate.

As an example you can check the code of the NoDe
